quest/blueprints/page/__init__.py
from quest.blueprints.page.views import page

quest/blueprints/page/views.py
from flask import Blueprint, render_template

page = Blueprint('page', __name__, template_folder='templates')


@page.route('/')
def home():
    return render_template('page/home.html')

@page.route('/single_trips')
def single_trips():
    return render_template('page/single_trips.html')


@page.route('/terms')
def terms():
    return render_template('page/terms.html')


@page.route('/privacy')
def privacy():
    return render_template('page/privacy.html')

quest/blueprints/page/templates/page/home.html
{% extends 'layouts/app.html' %}

{% block title %}Quest{% endblock %}
{% block meta_description %}Travel app{% endblock %}

{% block body %}
{{ super() }}

    <section id="banner" class="container">
        <div class="row banner-head">
            <div class="col-sm">

            </div>
            <div class="col-sm">
                <div class="banner-top">
                    <h2 class="banner-body-header">One Quest is better than two of something else</h2>
                </div>
                <div class="banner-body-text">
                    Quest is a this and that blah blah that lets you blah blah and also do a lot of plent many things, please ignore the text and focus on the design,, I basically was typing anything that came into my head because i dont want to use lorem ipsum text. Feel
                    the raw naked quest of the road
                </div>
            </div>
        </div>
    </section>

<!--DEALS SECTION/FEATURED QUESTS-->

    <div class="container">
      <h2 class="section-tag">Quest Deals</h2>
        <div class="row">
            <div class="col-lg">
                <div class="upcoming-trips">
                    <div class="row">
                        <div class="trip-item-1">
                            <div class="row trip-deatils">
                                <div class="col-md-3">
                                    <p class="upcoming-trips-price">
                                        N566,500
                                    </p>
                                </div>
                                <div class="col-md-9">
                                    <div class="upcoming-trips-text">
                                        <h3 class="upcoming-text-header"> Marzoma, Italy</h3>
                                        <p class="upcoming-text-desc">
                                            Exciting and diverse, the ancient feeling makes and breaks the touring rules. Scouring the globe for inspiration, our Italian based trips will bring out the purity in you Design Team is inspired by fashion’s most covetable trends; providing you with a
                                            cutting edge wardrobe season upon season.
                                        </p>
                                        <p class="upcoming-trip-date">
                                            15th December 2018
                                        </p>
                                    </div>

                                </div>
                                <div class="upcoming-trip-join">
                                  <span><img src="{{ url_for('static', filename='images/join-icon.png') }}" width="25" height="25"></span>
                                  <a href="{{url_for('page.index1')}}"><span> JOIN TRIP</span></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg">
                <div class="upcoming-trips">
                    <div class="row">
                        <div class="trip-item-2">
                            <div class="row trip-deatils">
                                <div class="col-md-3">
                                    <p class="upcoming-trips-price">
                                        N566,500
                                    </p>
                                </div>
                                <div class="col-md-9">
                                    <div class="upcoming-trips-text">
                                        <h3 class="upcoming-text-header"> Kutuput, Florida Bay</h3>
                                        <p class="upcoming-text-desc">
                                            Exciting and diverse, the ancient feeling makes and breaks the touring rules. Scouring the globe for inspiration, our Italian based trips will bring out the purity in you Design Team is inspired by fashion’s most covetable trends; providing you with a
                                            cutting edge wardrobe season upon season.
                                        </p>
                                        <p class="upcoming-trip-date">
                                            15th December 2018
                                        </p>
                                    </div>

                                </div>
                                <div class="upcoming-trip-join">
                                  <span><img src="{{ url_for('static', filename='images/join-icon.png') }}" width="25" height="25"></span>
                                  <a href="{{ url_for('page.single_trips') }}"><span>JOIN TRIP</span></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



<!--SMALL TRIP CARD SECTION-->


    <div class="container">
      <h2 class="section-tag">Featured trips</h2>
      <div class="row small-trips">
        <div class="col-md-3">
          <div class="card">
            <img src="{{ url_for('static', filename='images/home-img-3.jpg') }}" alt="Trips Avatar" style="width:100%">
            <div class="container">
              <h4 class="small-trips-desc"><b>OKPOLOPOLO, <br/>KOGI STATE</b></h4>
              <p class="small-trips-date">10TH, MARCH 2018</p>
            </div>
          </div>
        </div>

        <div class="col-md-3">
          <div class="card">
            <img src="{{ url_for('static', filename='images/home-img-4.jpg') }}" alt="Trips Avatar" style="width:100%">
            <div class="container">
              <h4 class="small-trips-desc"><b>RIO DE JANERO, <br />BRASIL</b></h4>
              <p class="small-trips-date">25TH, MAY 2018</p>
            </div>
          </div>
        </div>

        <div class="col-md-3">
          <div class="card">
            <img src="{{ url_for('static', filename='images/small-trips-3.jpg') }}" alt="Trips Avatar" style="width:100%">
            <div class="container">
              <h4 class="small-trips-desc"><b>HELSINKI USIMOO<br /> FINLAND</b></h4>
              <p class="small-trips-date">14TH, AUGUST 2018</p>
            </div>
          </div>
        </div>

        <div class="col-md-3">
          <div class="card">
            <img src="{{ url_for('static', filename='images/small-trips-4.jpg') }}" alt="Trips Avatar" style="width:100%">
            <div class="container">
              <h4 class="small-trips-desc"><b>SAMBISA FOREST, <br /> BORNO</b></h4>
              <p class="small-trips-date">19TH, SEPTEMBER 2018</p>
            </div>
          </div>
        </div>
      </div>
    </div>




    <div class="container">
      <div class="row small-trips">
        <div class="col-md-3">
          <div class="card">
            <img src="{{ url_for('static', filename='images/small-trips-5.jpg') }}" alt="Trips Avatar" style="width:100%">
            <div class="container">
              <h4 class="small-trips-desc"><b>OKPOLOPOLO, <br/>KOGI STATE</b></h4>
              <p class="small-trips-date">10TH, MARCH 2018</p>
            </div>
          </div>
        </div>

        <div class="col-md-3">
          <div class="card">
            <img src="{{ url_for('static', filename='images/small-trips-6.jpg') }}" alt="Trips Avatar" style="width:100%">
            <div class="container">
              <h4 class="small-trips-desc"><b>RIO DE JANERO, <br />BRASIL</b></h4>
              <p class="small-trips-date">25TH, MAY 2018</p>
            </div>
          </div>
        </div>

        <div class="col-md-3">
          <div class="card">
            <img src="{{ url_for('static', filename='images/small-trips-7.jpg') }}" alt="Trips Avatar" style="width:100%">
            <div class="container">
              <h4 class="small-trips-desc"><b>HELSINKI USIMOO<br /> FINLAND</b></h4>
              <p class="small-trips-date">14TH, AUGUST 2018</p>
            </div>
          </div>
        </div>

        <div class="col-md-3">
          <div class="card">
            <img src="{{ url_for('static', filename='images/small-trips-8.jpg') }}" alt="Trips Avatar" style="width:100%">
            <div class="container">
              <h4 class="small-trips-desc"><b>SAMBISA FOREST, <br /> BORNO</b></h4>
              <p class="small-trips-date">19TH, SEPTEMBER 2018</p>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div>
      <div class="create-trip">
        <div class="row">
          <div class="col-md-3">


          </div>
          <div class="col-md-9">
            <h4 class="create-trip-top">Cant find where you want to go?</h4>
            <div class="create-trip-button">
              CREATE A TRIP
            </div>
            <p class="create-trip-text">
              Do you have a place you wanna go thats not on our list of featured trips,
              why not create a trip, our team of something will get an estimate of the
              cost and other requirements and then we will publish
              among our featured trips, you also have the option of making a trip private
              and sharing with just family and friends.
            </p>

          </div>
        </div>
      </div>
    </div>

{% endblock %}

quest/blueprints/page/templates/page/index1.html
{% extends 'layouts/app.html' %}

{% block title %}Quest{% endblock %}
{% block meta_description %}Travel app{% endblock %}

{% block body %}
{{ super() }}

    <!--SINGLE TRIPS-->


    <section>
        <div class="container">
          <div class="single-trips-header">
            <div class="row">
                <div class="col-md-6">
                    <h3>Inapueto, Morata de grannes <br /> Helsinki, Finland</h3>
                </div>
                <div class="col-md-6">
                    <span>
              <div class="single-trip-save">
              <span><img src="img/new/save-icon.png" width="25" height="25"></span>
                    <span class="single-save-text">SAVE TO MY TRIPS</span>
                </div>
                </span>
                <span><a href="#">
            <div class="single-trip-share">
              <span><img src="img/new/share-icon.png" width="25" height="25"></span>
                <span class="single-save-text">SHARE</span>
            </div></a>
            </span>
        </div>
        </div>
        </div>

        <div class="single-trip-banner">
            <div class="single-banner-details">
                <span class="details-hero">
                    "A Central and Stylish Place in Finland"
                </span>
                <p>
                    14th June 2018
                </p>
                <p>
                    PRICE: <span>N789,450</span>
                </p>
                <div class="single-trip-join">
                    <span><img src="img/new/join-icon-yellow.png" width="25" height="25"></span>
                    <span class="single-join-text">JOIN TRIP</span>
                </div>
                <span class="single-time">
                    Time Remaining: <br /> <span>21 days, 21:05:33</span>
                </span>
            </div>
        </div>


        <div class="row">
            <div class="col-md-8 tabs">
                <input type="radio" name="tabs" id="tabone" checked="checked">
                <label for="tabone">Summary</label>
                <div class="tab">
                    <h1>Summary</h1>
                    <p>
                        Now that ProductList is managing the products in state, we’re poised to make modifications to this data in response to user input. Specifically, we want to increment the votes property on a product when the user votes for it. We just discussed that we
                        can only make state modifications using this.setState(). So while a component can update its state, we should treat the this.state object as immutable. As touched on earlier, if we treat an array or object as immutable we never
                        make modifications to it. For example, let’s say we have an array of numbers in state: Now that ProductList is managing the products in state, we’re poised to make modifications to this data in response to user input. Specifically,
                        we want to increment the votes property on a product when the user votes for it. We just discussed that we can only make state modifications using this.setState(). So while a component can update its state, we should treat the
                        this.state object as immutable. As touched on earlier, if we treat an array or object as immutable we never make modifications to it. For example, let’s say we have an array of numbers in state:
                    </p>
                </div>

                <input type="radio" name="tabs" id="tabtwo">
                <label for="tabtwo">Travel Details</label>
                <div class="tab">
                    <h1>Travel Details</h1>
                    <p>
                        <ul>
                            <li>Bag</li>
                            <li>Shoe</li>
                            <li>Clothe</li>
                            <li>Jacket</li>
                            <li>Hat</li>
                        </ul>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus inventore perferendis cumque recusandae modi quasi minus laborum, ab at quod aliquid veritatis mollitia similique eos totam quisquam reiciendis, placeat temporibus! So while a component can
                        update its state, we should treat the this.state object as immutable. As touched on earlier, if we treat an array or object as immutable we never make modifications to it. For example, let’s say we have an array of numbers in state:
                    </p>
                </div>

                <input type="radio" name="tabs" id="tabthree">
                <label for="tabthree">Map</label>
                <div class="tab">
                    <h1>Map</h1>
                    <p>Map</p>
                </div>

            </div>

            <div class="col-md-4 people-going">
              <img src="img/new/going-avatar.png" alt="going-img">
              <p class="going-text">
                <a>27 People Going</a> <br />
                <a>Find out who is going</a>
              </p>
              <div class="single-trip-join">
                  <span><img src="img/new/join-icon-yellow.png" width="25" height="25"></span>
                  <span class="single-join-text">JOIN TRIP</span>
              </div>
            </div>

        </div>
        </div>
    </section>

    &nbsp;




  {% endblock %}

quest/blueprints/page/templates/page/index2.html
{% extends 'layouts/base.html' %}

{% block title %}Quest{% endblock %}
{% block meta_description %}Travel app{% endblock %}

{% block body %}
		<!--Prompt for vevry old browsers>
        <!-[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

        <!-- Site Content -->

		<p>QUEST</p>

{% endblock %}

quest/blueprints/page/templates/page/privacy.html
{% extends 'layouts/base.html' %}

{% block title %}Privacy Policy{% endblock %}
{% block heading %}<h2>Privacy Policy</h2>{% endblock %}

{% block body %}
  <p>
    This privacy policy discloses the privacy practices for 
    <a href="http://{{ config.get('SERVER_NAME') }}">
      http://{{ config.get('SERVER_NAME') }}
    </a>.
    This privacy policy applies solely to information collected by this web
    site. It will notify you of the following:
  </p>
  <ul>
    <li>
      What personally identifiable information is collected from you through
      the web site, how it is used and with whom it may be shared.
    </li>
    <li>
      What choices are available to you regarding the use of your data.
    </li>
    <li>
      The security procedures in place to protect the misuse of your information.
    </li>
    <li>How you can correct any inaccuracies in the information.</li>
  </ul>

  <hr/>

  <h3>Information collection, use, and sharing</h3>
  <p>
    We are the sole owners of the information collected on this site. We
    only have access to/collect information that you voluntarily give us via
    email or other direct contact from you. We will not sell or rent this
    information to anyone.
  </p>
  <p>
    We will use your information to respond to you, regarding the reason you
    contacted us. We will not share your information with any third party
    outside of our organization, other than as necessary to fulfill your
    request, e.g. to process a credit card.
  </p>
  <p>
    Unless you ask us not to, we may contact you via email in the future to
    tell you about specials, new products or services, or changes to this
    privacy policy.
  </p>
    
  <hr/>
  
  <h3>Your access to and control over information</h3>
  <p>
    You may opt out of any future contacts from us at any time. You can do the
    following at any time by contacting us via the email address or phone
    number given on our website:
  </p>
  <ul>
    <li>See what data we have about you, if any.</li>
    <li>Change/correct any data we have about you.</li>
    <li>Have us delete any data we have about you.</li>
    <li>Express any concern you have about our use of your data.</li>
  </ul>
  
  <hr/>
  
  <h3>Security</h3>
  <p>
    We take precautions to protect your information. When you submit sensitive
    information via the website, your information is protected both online and
    offline.
  </p>
  <p>
    Wherever we collect sensitive information (such as credit card data),
    that information is encrypted and transmitted to us in a secure way.
    You can verify this by looking for a closed lock icon at the bottom of your
    web browser, or looking for "https" at the beginning of the address of
    the web page.
  </p>
  <p>
    While we use encryption to protect sensitive information transmitted
    online, we also protect your information offline. Only employees who
    need the information to perform a specific job (for example, billing or
    customer service) are granted access to personally identifiable information.
    The computers/servers in which we store personally identifiable information
    are kept in a secure environment.
  </p>

  <h4>Credit card information</h4>
  <p>
    We do not store your credit card information directly. It is passed
    through to a third party credit card processing merchant using 128-bit
    SSL encryption. We only keep your credit card's brand, last 4 digits and
    expiration date to assist and remind you of any billing related issues.
  </p>

  <hr/>

  <h3>Cookies</h3>
  <p>
    We use "cookies" on this site. A cookie is a piece of data stored on a
    site visitor's hard drive to help us improve your access to our site
    and identify repeat visitors to our site. For instance, when we use a
    cookie to identify you, you would not have to log in with a password more
    than once, thereby saving time while on our site. Cookies can also enable us
    to track and target the interests of our users to enhance the experience
    on our site. Usage of a cookie is in no way linked to any personally
    identifiable information on our site.
  </p>
  <p>
    If you do not want to be tracked by Google Analytics you may opt-out using
    <a target="_blank" href="https://tools.google.com/dlpage/gaoptout/">
      Google&#39;s official opt-out browser add-on
    </a>.
  </p>

  <hr/>
  
  <h3>Links</h3>
  <p>
    This web site contains links to other sites. Please be aware that we are
    not responsible for the content or privacy practices of such other sites.

    We encourage our users to be aware when they leave our site and to read
    the privacy statements of any other site that collects personally
    identifiable information.
  </p>

  <hr/>
  
  <h3>Updates</h3>
  <p>
    Our privacy policy may change from time to time and all updates will be
    posted on this page.
  </p>

  <p>
    If you feel that we are not abiding by this privacy policy, you should
    contact us immediately via telephone at XXX-XXX-XXXX or via email.
  </p>

  <small class="text-muted">Last updated April 1st 2042</small>
{% endblock %}

quest/blueprints/page/templates/page/single_trips.html
{% extends 'layouts/app.html' %}

{% block title %}Quest{% endblock %}
{% block meta_description %}Travel app{% endblock %}

{% block body %}
{{ super() }}
    <!--Prompt for vevry old browsers>
        <!-[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- Site Content -->

    <!-- NAVIGATION -->

    <!--SINGLE TRIPS-->


    <section>
        <div class="container">
          <div class="single-trips-header">
            <div class="row">
                <div class="col-md-6">
                    <h3>Inapueto, Morata de grannes <br /> Helsinki, Finland</h3>
                </div>
                <div class="col-md-6">
                    <span>
              <div class="single-trip-save">
              <span><img src="{{ url_for('static', filename='images/save-icon.png') }}" width="25" height="25"></span>
                    <span class="single-save-text">SAVE TO MY TRIPS</span>
                </div>
                </span>
                <span><a href="#">
            <div class="single-trip-share">
              <span><img src="{{ url_for('static', filename='images/share-icon.png') }}" width="25" height="25"></span>
                <span class="single-save-text">SHARE</span>
            </div></a>
            </span>
        </div>
        </div>
        </div>

        <div class="single-trip-banner">
            <div class="single-banner-details">
                <span class="details-hero">
                    "A Central and Stylish Place in Finland"
                </span>
                <p>
                    14th June 2018
                </p>
                <p>
                    PRICE: <span>N789,450</span>
                </p>
                <div class="single-trip-join">
                    <span><img src="{{ url_for('static', filename='images/join-icon-yellow.png') }}" width="25" height="25"></span>
                    <span class="single-join-text">JOIN TRIP</span>
                </div>
                <span class="single-time">
                    Time Remaining: <br /> <span>21 days, 21:05:33</span>
                </span>
            </div>
        </div>


        <div class="row">
            <div class="col-md-8 tabs">
                <input type="radio" name="tabs" id="tabone" checked="checked">
                <label for="tabone">Summary</label>
                <div class="tab">
                    <h1>Summary</h1>
                    <p>
                        Now that ProductList is managing the products in state, we’re poised to make modifications to this data in response to user input. Specifically, we want to increment the votes property on a product when the user votes for it. We just discussed that we
                        can only make state modifications using this.setState(). So while a component can update its state, we should treat the this.state object as immutable. As touched on earlier, if we treat an array or object as immutable we never
                        make modifications to it. For example, let’s say we have an array of numbers in state: Now that ProductList is managing the products in state, we’re poised to make modifications to this data in response to user input. Specifically,
                        we want to increment the votes property on a product when the user votes for it. We just discussed that we can only make state modifications using this.setState(). So while a component can update its state, we should treat the
                        this.state object as immutable. As touched on earlier, if we treat an array or object as immutable we never make modifications to it. For example, let’s say we have an array of numbers in state:
                    </p>
                </div>

                <input type="radio" name="tabs" id="tabtwo">
                <label for="tabtwo">Travel Details</label>
                <div class="tab">
                    <h1>Travel Details</h1>
                    <p>
                        <ul>
                            <li>Bag</li>
                            <li>Shoe</li>
                            <li>Clothe</li>
                            <li>Jacket</li>
                            <li>Hat</li>
                        </ul>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus inventore perferendis cumque recusandae modi quasi minus laborum, ab at quod aliquid veritatis mollitia similique eos totam quisquam reiciendis, placeat temporibus! So while a component can
                        update its state, we should treat the this.state object as immutable. As touched on earlier, if we treat an array or object as immutable we never make modifications to it. For example, let’s say we have an array of numbers in state:
                    </p>
                </div>

                <input type="radio" name="tabs" id="tabthree">
                <label for="tabthree">Map</label>
                <div class="tab">
                    <h1>Map</h1>
                    <p>Map</p>
                </div>

            </div>

            <div class="col-md-4 people-going">
              <img src="img/new/going-avatar.png" alt="going-img">
              <p class="going-text">
                <a>27 People Going</a> <br />
                <a>Find out who is going</a>
              </p>
              <div class="single-trip-join">
                  <span><img ssrc="{{ url_for('static', filename='images/join-icon-yellow.png') }}" width="25" height="25"></span>
                  <span class="single-join-text">JOIN TRIP</span>
              </div>
            </div>

        </div>
        </div>
    </section>

    &nbsp;

{% endblock %}